# This content is generated by {GENERATOR}
load("@@//toolchains/dot:dot.bzl", "dot_toolchain")

dot_toolchain(
    name = "dot_auto",
    path = "{RPMBUILD_PATH}",
    version = "{RPMBUILD_VERSION}",
)

toolchain(
    name = "dot_auto_toolchain",
    toolchain = ":dot_auto",
    toolchain_type = "@@//toolchains/dot:dot_toolchain_type",
)
