name: Bazel build

env:
  HOMEBREW_NO_AUTO_UPDATE: 1

on: [push]

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      # action runners have bazelisk: - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2
      - run: bazel build //...
